function output = exampleFunction(number)

output = random('Normal',1,5)

% exception = MException("TestError:Example", "This is an exception or an error!");
% throw(exception)

end